FROM anapsix/alpine-java
COPY out/Client.jar /home/Client.jar
CMD ["java","-jar","/home/Client.jar"]
#   Kill container
#docker rm -f client1
#   Delete image
#sudo docker rmi client
#   Rebuild
#sudo docker build -t client .
#   run
#sudo docker run -i -t --name client1 client
#   logs
#sudo docker logs client1
