FROM anapsix/alpine-java
COPY out/Client.jar /home/Client.jar
CMD ["java","-jar","/home/Client.jar"]
#sudo ip addr add 192.168.1.193/24 dev enp0s25
#Rebuild
#Kill && delete
#sudo docker rmi
#Rebuild
#sudo docker build -t client .
#run
#sudo docker run -i -t --name client1 -p 192.168.1.193:6789:6789 client
#logs
#sudo docker logs client1
