FROM anapsix/alpine-java
COPY out/Server.jar /home/Server.jar
CMD ["java","-jar","/home/Server.jar"]
#sudo ip addr add 192.168.1.10/24 dev enp0s25
#Rebuild
#Kill && delete
#sudo docker rmi
#Rebuild
#sudo docker build -t srv .
#run
#sudo docker run -d --name srv1 -p 192.168.1.10:6789:6789 srv
#logs
#sudo docker logs srv1
