FROM anapsix/alpine-java
COPY out/Redirect.jar /home/Redirect.jar
CMD ["java","-jar","/home/Redirect.jar"]
#   Kill container
#docker rm -f redir1
#   Delete image
#sudo docker rmi redir
#   Rebuild
#sudo docker build -t redir .
#   run
#sudo docker run -d --name redir1 redir
#   logs
#sudo docker logs redir1
