FROM anapsix/alpine-java
COPY out/Redirect.jar /home/Redirect.jar
CMD ["java","-jar","/home/Redirect.jar"]
#sudo ip addr add 192.168.1.100/24 dev enp0s25
#Rebuild
#Kill && delete
#sudo docker rmi
#Rebuild
#sudo docker build -t redir .
#run
#sudo docker run -d --name redir1 redir
#logs
#sudo docker logs redir3
